" Enable syntax highlighting
syntax on

" Color scheme to apply
colorscheme murphy

" Show line number on the gutter
set number

" Show incremental match while searching
set incsearch

" Highlight incremental search
set hlsearch

" Powerline status bar
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup


" Always display the status line, even if only one window is displayed
set laststatus=2

" Command line completion
set wildmenu

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Indentation settings for using 4 spaces instead of tabs.
" Do not change 'tabstop' from its default value of 8 with this setup.
set shiftwidth=4
set softtabstop=4
set expandtab
