syntax on               " Enable syntax highlighting

" Color scheme to apply
"colorscheme editPlus
colorscheme horseradish256

set number              " Show line number on the gutter
set showmatch           " Highlight matching brace

" Powerline status bar
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup


set laststatus=2            " Always display the status line, even if only one window is displayed
set wildmenu                " Command line completion

"""""""""""""""""
" Search settings
"""""""""""""""""
set ignorecase              " Use case insensitive search, except when using capital letters
set smartcase               " Enable smart-case search
set hlsearch                " Highlight all search results
set incsearch               " Show incremental match while searching

""""""""""""""""""""""""""""""""""
" Tab and indentation settings
""""""""""""""""""""""""""""""""""
" Indentation settings for using 4 spaces instead of tabs.
" Do not change 'tabstop' from its default value of 8 with this setup.
set shiftwidth=4            " Number of auto-indent spaces
set softtabstop=4
set expandtab               " Use spaces instead of tabs
" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

set autochdir               " Change working directory to open buffer
set autowriteall            " Auto-write all file changes
