#!/bin/bash

code --install-extension EditorConfig.EditorConfig
code --install-extension Tyriar.sort-lines
code --install-extension abadi199.elm-format
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.Bookmarks
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension azemoh.one-monokai
code --install-extension codezombiech.gitignore
code --install-extension cssho.vscode-svgviewer
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension felipecaputo.git-project-manager
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension HookyQR.beautify
code --install-extension joaompinto.asciidoctor-vscode
code --install-extension mariorodeghiero.vue-theme
code --install-extension mechatroner.rainbow-csv
code --install-extension mohsen1.prettify-json
code --install-extension ms-vscode.Go
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PKief.material-icon-theme
code --install-extension robertohuertasm.vscode-icons
code --install-extension sbrink.elm
code --install-extension sldobri.nord-5-stars
code --install-extension stayfool.vscode-asciidoc
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension teabyii.ayu
code --install-extension tht13.html-preview-vscode
code --install-extension vangware.dark-plus-material
code --install-extension vscodevim.vim
code --install-extension vsmobile.vscode-react-native
code --install-extension waderyan.gitblame
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yamenarahman.nord-extra-dark
code --install-extension zhuangtongfa.Material-theme